"""order publik alamat konfirmasi ongkir

Revision ID: 05d2c7bb1ab8
Revises: 9c89d48ded16
Create Date: 2026-09-10 14:37:59.248957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '05d2c7bb1ab8'
down_revision: Union[str, Sequence[str], None] = '9c89d48ded16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('no_telepon', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('provinsi', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('kota', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('kecamatan', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('kode_pos', sa.String(length=10), nullable=True))
    op.add_column('orders', sa.Column('nama_jalan', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('detail_lainnya', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('status_konfirmasi', sa.String(length=20), server_default='menunggu', nullable=False))
    op.add_column('orders', sa.Column('ongkir', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('orders', 'uang_dibayar')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('uang_dibayar', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'ongkir')
    op.drop_column('orders', 'status_konfirmasi')
    op.drop_column('orders', 'detail_lainnya')
    op.drop_column('orders', 'nama_jalan')
    op.drop_column('orders', 'kode_pos')
    op.drop_column('orders', 'kecamatan')
    op.drop_column('orders', 'kota')
    op.drop_column('orders', 'provinsi')
    op.drop_column('orders', 'no_telepon')
    # ### end Alembic commands ###
