"""produk sekarang punya varian berat

Revision ID: 071227c8e8d6
Revises: f5ae945e1978
Create Date: 2026-09-09 09:14:40.034119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '071227c8e8d6'
down_revision: Union[str, Sequence[str], None] = 'f5ae945e1978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produk_varian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produk_id', sa.Integer(), nullable=False),
    sa.Column('berat', sa.Float(), nullable=False),
    sa.Column('harga', sa.Integer(), nullable=False),
    sa.Column('stok', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['produk_id'], ['produk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produk_varian_id'), 'produk_varian', ['id'], unique=False)
    op.add_column('order_items', sa.Column('produk_varian_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('order_items_ibfk_2'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'produk_varian', ['produk_varian_id'], ['id'])
    op.drop_column('order_items', 'produk_id')
    op.add_column('pasokan', sa.Column('produk_varian_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('pasokan_ibfk_2'), 'pasokan', type_='foreignkey')
    op.create_foreign_key(None, 'pasokan', 'produk_varian', ['produk_varian_id'], ['id'])
    op.drop_column('pasokan', 'produk_id')
    op.add_column('penyesuaian_stok', sa.Column('produk_varian_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('penyesuaian_stok_ibfk_1'), 'penyesuaian_stok', type_='foreignkey')
    op.create_foreign_key(None, 'penyesuaian_stok', 'produk_varian', ['produk_varian_id'], ['id'])
    op.drop_column('penyesuaian_stok', 'produk_id')
    op.drop_column('produk', 'stok')
    op.drop_column('produk', 'harga')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produk', sa.Column('harga', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('produk', sa.Column('stok', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('penyesuaian_stok', sa.Column('produk_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'penyesuaian_stok', type_='foreignkey')
    op.create_foreign_key(op.f('penyesuaian_stok_ibfk_1'), 'penyesuaian_stok', 'produk', ['produk_id'], ['id'])
    op.drop_column('penyesuaian_stok', 'produk_varian_id')
    op.add_column('pasokan', sa.Column('produk_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pasokan', type_='foreignkey')
    op.create_foreign_key(op.f('pasokan_ibfk_2'), 'pasokan', 'produk', ['produk_id'], ['id'])
    op.drop_column('pasokan', 'produk_varian_id')
    op.add_column('order_items', sa.Column('produk_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_ibfk_2'), 'order_items', 'produk', ['produk_id'], ['id'])
    op.drop_column('order_items', 'produk_varian_id')
    op.drop_index(op.f('ix_produk_varian_id'), table_name='produk_varian')
    op.drop_table('produk_varian')
    # ### end Alembic commands ###
