"""sinkronkan tabel produksi (penerimaan_bahan_baku, penggilingan, pengemasan)

Revision ID: 088f402eae9a
Revises: a756767ed2c1
Create Date: 2026-09-21 09:26:27.210278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '088f402eae9a'
down_revision: Union[str, Sequence[str], None] = 'a756767ed2c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('penerimaan_bahan_baku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pemasok_id', sa.Integer(), nullable=False),
    sa.Column('produk_id', sa.Integer(), nullable=False),
    sa.Column('berat_kg', sa.Float(), nullable=False),
    sa.Column('harga_per_kg', sa.Integer(), nullable=True),
    sa.Column('status_mutu', sa.String(length=20), server_default='menunggu', nullable=False),
    sa.Column('catatan', sa.String(length=255), nullable=True),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pemasok_id'], ['pemasok.id'], ),
    sa.ForeignKeyConstraint(['produk_id'], ['produk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_penerimaan_bahan_baku_id'), 'penerimaan_bahan_baku', ['id'], unique=False)
    op.create_table('pengemasan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produk_varian_id', sa.Integer(), nullable=False),
    sa.Column('jumlah_pcs', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['produk_varian_id'], ['produk_varian.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pengemasan_id'), 'pengemasan', ['id'], unique=False)
    op.create_table('penggilingan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('penerimaan_id', sa.Integer(), nullable=False),
    sa.Column('berat_masuk_kg', sa.Float(), nullable=False),
    sa.Column('berat_hasil_kg', sa.Float(), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['penerimaan_id'], ['penerimaan_bahan_baku.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_penggilingan_id'), 'penggilingan', ['id'], unique=False)
    op.drop_index(op.f('ix_pasokan_id'), table_name='pasokan')
    op.drop_table('pasokan')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pasokan',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pemasok_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('jumlah', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tanggal', mysql.DATETIME(), nullable=True),
    sa.Column('produk_varian_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pemasok_id'], ['pemasok.id'], name=op.f('pasokan_ibfk_1')),
    sa.ForeignKeyConstraint(['produk_varian_id'], ['produk_varian.id'], name=op.f('pasokan_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_pasokan_id'), 'pasokan', ['id'], unique=False)
    op.drop_index(op.f('ix_penggilingan_id'), table_name='penggilingan')
    op.drop_table('penggilingan')
    op.drop_index(op.f('ix_pengemasan_id'), table_name='pengemasan')
    op.drop_table('pengemasan')
    op.drop_index(op.f('ix_penerimaan_bahan_baku_id'), table_name='penerimaan_bahan_baku')
    op.drop_table('penerimaan_bahan_baku')
    # ### end Alembic commands ###
