"""tambah kolom uang dibayar di order

Revision ID: 9c89d48ded16
Revises: 071227c8e8d6
Create Date: 2026-09-09 14:52:15.582240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c89d48ded16'
down_revision: Union[str, Sequence[str], None] = '071227c8e8d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('uang_dibayar', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'uang_dibayar')
    # ### end Alembic commands ###
