"""tambah tabel penyesuaian stok

Revision ID: f5ae945e1978
Revises: 058ce90678e0
Create Date: 2026-09-08 10:36:50.429208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5ae945e1978'
down_revision: Union[str, Sequence[str], None] = '058ce90678e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('penyesuaian_stok',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produk_id', sa.Integer(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('alasan', sa.String(length=50), nullable=False),
    sa.Column('keterangan', sa.String(length=255), nullable=True),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['produk_id'], ['produk.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_penyesuaian_stok_id'), 'penyesuaian_stok', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_penyesuaian_stok_id'), table_name='penyesuaian_stok')
    op.drop_table('penyesuaian_stok')
    # ### end Alembic commands ###
